# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update', '更改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
